/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Erina eka syaharani (https://sketchfab.com/erinaekasyaharani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/butterfly-blue-637d2ef1210d43d5b743fea17c329a1d
Title: Butterfly blue
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import Scene from "@/assets/butterfly_blue.glb";

const ShiningButterFly = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(Scene);
  const { actions, names } = useAnimations(animations, group);
  useEffect(() => {
    actions[names[0]]?.reset().play();
  }, [animations]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group
              name="Lamp"
              position={[-2.783, -3.63, 2.792]}
              rotation={[-0.268, 0.602, 1.931]}
            >
              <group name="Lamp_1" />
            </group>
            <group
              name="Mesh001"
              rotation={[-1.903, 0, -Math.PI]}
              scale={0.017}
            >
              <mesh
                name="Mesh001_0"
                castShadow
                receiveShadow
                geometry={nodes.Mesh001_0.geometry}
                material={materials.mat1}
              />
              <group name="Mesh006" rotation={[0, 0, 0.843]}>
                <mesh
                  name="Mesh006_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh006_0.geometry}
                  material={materials.mat1}
                />
              </group>
              <group name="Mesh004" rotation={[0, 0, -0.861]}>
                <mesh
                  name="Mesh004_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh004_0.geometry}
                  material={materials.mat1}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};
export default ShiningButterFly;
