export const PERSONAL_PROJECTS = [
  {
    id: 1,
    color: "from-purple-300 to-red-300",
    title: "Disney Clone",
    desc: "Disney Clone built using ReactJs and Firebase and TMDB APIs. It also has AI search functionality using which you can search movies based on or mood by typing any kind of query in searchbar",
    img: "",
    link: "https://lama.dev",
    video: "/videos/disney-clone.mp4",
    techStacks: [
      "React js",
      "Firebase",
      "Styled Components",
      "Slick Carousel",
      "React Slick",
    ],
  },
  {
    id: 2,
    color: "from-purple-300 to-red-300",
    title: "iNotebook",
    desc: "iNotebook is a full-stack application built using the MERN stack. It helps you to store your notes securely on the cloud. It also gives you the functionality to edit and delete your previous written notes.",
    img: "",
    link: "https://lama.dev",
    video: "/videos/inotebook.mp4",
    techStacks: [
      "React js",
      "Node js",
      "Mongo DB",
      "Mongoose",
      "Exress js",
      "Bcrypt js",
      "Bootstrap",
    ],
  },
  {
    id: 3,
    color: "from-purple-300 to-red-300",
    title: "Meditation App",
    desc: "This app can be used for meditation and unwinding. It has 4 different themes containing different soothing sounds of nature like the sound of birds, the sound of rain, and the sound of sea waves, which are combined with the calming music of piano & flute.",
    img: "",
    link: "https://lama.dev",
    video: "/videos/musing.mp4",
    techStacks: ["HTML", "CSS", "Javascript"],
  },
  {
    id: 4,
    color: "from-purple-300 to-red-300",
    title: "Images Gallary",
    desc: "Click on the images to see the beautiful animations :) along with inspiraing quotes to make your day",
    img: "",
    link: "https://lama.dev",
    video: "/videos/image-gallary.mp4",
    techStacks: ["HTML", "CSS"],
  },
];
